# .github/1password/secrets.yml
env:
  FIREBASE_DEPLOY_TOKEN: "op://BYB LMS CI/Firebase Deploy Token – spike-education-ceb97/token"
  CF_DNS_TOKEN:         "op://BYB LMS CI/Cloudflare DNS Token/api_key"
  SUPABASE_SERVICE_KEY: "op://BYB LMS CI/Supabase Service Role/key"
