# 2️⃣  Load secrets from 1Password
- name: Load 1Password secrets
  uses: 1Password/load-secrets-action@v2
  with:
    export-env: true                # makes them $ENV variables
  env:
    OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    # 🔑 1Password secret references → the env vars you’ll use later
    FIREBASE_DEPLOY_TOKEN: "op://BYB LMS CI/Firebase Deploy Token – spike-education-ceb97/token"
    SUPABASE_SERVICE_KEY: "op://BYB LMS CI/Supabase Service Role/key"
    # (omit CF_DNS_TOKEN until you have Cloudflare ready)
