# 2️⃣  Load secrets from 1Password
- name: Load 1Password secrets
  uses: 1Password/load-secrets-action@v2
  with:
    export-env: true
    secrets: |
      FIREBASE_DEPLOY_TOKEN=op://BYB LMS CI/Firebase Deploy Token – spike-education-ceb97/token
      SUPABASE_SERVICE_KEY=op://BYB LMS CI/Supabase Service Role/key
  env:
    OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
