# .github/workflows/deploy.yml
name: Build & Deploy LMS

on:
  push:
    branches: [ main ]          # run on every push to main
  workflow_dispatch:            # ↩ optional manual run button

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣  Load secrets from 1Password
      - name: Load 1Password secrets
        uses: 1Password/load-secrets-action@v2
        with:
          export-env: true
          secrets-file-path: .github/1password/secrets.yml
        env:
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          OP_CONNECT_HOST:  https://connect.1password.com

      # 3️⃣  Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 4️⃣  Install deps & run tests
      - name: Fetch packages
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

      # 5️⃣  Build release bundle
      - name: Build web release
        run: flutter build web --release

      # 6️⃣  Deploy to Firebase Hosting (preview channel)
      - name: Deploy to Firebase Hosting (staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          channelId: staging
          projectId: spike-educati
